### ISSUE TITLE
Dynamically retrieve correct IP address

### ISSUE THREAD

**Issue by shortpoet** [Azure/aci-deploy#15]
When I create a container it shows the ip address.  I can retrieve that ip address with the below command.

```bash
cmd="az container show \
-n $CONTAINER \
--query ipAddress.ip \
-o tsv \
-g $RG"
```
The problem is, that is not the ip address under which the container actually runs.  When checking container logs in azure portal, I see the error that says the server is trying to connect to my database under a different ip.  I need that ip to be able to configure server firewall.

```bash
  az sql server firewall-rule create \
  -g $DB_RG \
  -s $DB_SERVER \
  -n $FIREWALL_RULE \
  --start-ip-address $IP \
  --end-ip-address $IP

```

How to retrieve the correct ip dynamically so it can be set in create-container script?

**Comment by anraghun** [comment]
@shortpoet This repo is used to track issues for the `aci-deploy` action only.
