### ISSUE TITLE
restart-policy only accepts "Always" value

### ISSUE THREAD

**Issue by iluxa86** [Azure/aci-deploy#17]
https://github.com/Azure/aci-deploy/blob/ee70b52b1aecbaa770d6c230989ac1cfa66a9aed/src/taskparameters.ts#L105

There is a bug here.
This will throw error for anything except "Always"

**Comment by iluxa86** [comment]
this line should be changed to
`if(restartPolicy not in ("Always", "OnFailure", "Never")) {`

But I do not have permissions to submit PR

**Comment by iluxa86** [comment]
I did not realize it is TS code.
The code should be:
`if(!["Always", "OnFailure", "Never"].includes(restartPolicy)) { 
`

**Comment by anraghun** [comment]
@narula0781

**Comment by alexlydiate** [comment]
We've also met this - a real pain. Seems @iluxa86 has given the fix three months ago...

**Comment by alexlydiate** [comment]
@iluxa86 certainly pointed in the right direct - pull request https://github.com/Azure/aci-deploy/pull/38 fixes this, which on our fork is working fine.

**Comment by huinalam** [comment]
when is it resolved?
restart policy bug is still alive.

**Comment by alexlydiate** [comment]
@huinalam I've given up on this. I met another, similar bug, and concluded there must be a better way. And there is - just use https://github.com/azure/cli directly, and then you can do whatever the CLI allows you too, and you end up with a better understanding of what's going on, much more power over it - and, it works.

**Comment by kanika1894** [comment]
If I am not wrong, #43 this solves the issue, right? this solves the issue, right?

**Comment by jseadragon** [comment]
It *appears* this has been fixed in `master`, but we do not have a new release cut. What's the ETA on getting a new tag with this change?

**Comment by kanika1894** [comment]
@jseadragon @iluxa86  @alexlydiate 
This has been fixed in the patch version.
Can you please verify if using aci-deploy@v1.1.1 solves the issue and works well?

**Comment by kanika1894** [comment]
Fixed in v1 as well.
