### ISSUE TITLE
Warning: `set-env` command is deprecated 

### ISSUE THREAD

**Issue by mbtools** [Azure/aci-deploy#22]
During `azure/aci-deploy@v1` you get the following warning.

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

![image](https://user-images.githubusercontent.com/59966492/95687239-65907080-0bd0-11eb-88d6-7758a3c87910.png)

**Comment by nosvalds** [comment]
Adding that is an Error now, and will be disabled on November 16th

```
Run azure/aci-deploy@v1
26
Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by remyjette** [comment]
November 16th has passed and the error has now changed:

```
Error: Unable to process command '::set-env name=AZURE_HTTP_USER_AGENT::' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by remyjette** [comment]
`set-env` was being used by `@actions/core`, which `aci-deploy` relies on.
`@actions/core` resolved the issue in https://github.com/actions/toolkit/pull/571.

I just tested forking this repo and upgrading to `@actions/core` 1.2.6 (latest), and the error goes away. Published #27 to upgrade it here.

**Comment by mitsha-microsoft** [comment]
#18 is merged. I think it should resolve this issue

**Comment by WardMaes** [comment]
The error is still showing, preventing deployments.

**Comment by remyjette** [comment]
A new version of the action will need to be created first. See #26

**Comment by JoeMarkov** [comment]
My deployments are down due to this, any plan when this can be fixed?
