### ISSUE TITLE
Request for new version of aci-deploy action

### ISSUE THREAD

**Issue by jesseward** [Azure/aci-deploy#26]
Logging this request to tag a new release of this action as it looks like a fix has been merged that addresses a bug relating to the parsing of secrets/strings. There have been a few issues/PR raised for the handling of `=` in environment secrets
* https://github.com/Azure/aci-deploy/issues/13
* https://github.com/Azure/aci-deploy/pull/10
* https://github.com/Azure/aci-deploy/pull/14
* https://github.com/Azure/aci-deploy/pull/8

--

The following was _Originally posted by @mitsha-microsoft in https://github.com/Azure/aci-deploy/pull/8#issuecomment-720900090_

@jesseward yes simply pointing to `aci-deploy@master` won't work since it's not a good advice to point directly to the master branch. Forwarding your issue to @narula0781 and @ashishonce who can release a new version of this action with the updates.

**Comment by jesseward** [comment]
Tagging @narula0781 and @ashishonce here as well.

**Comment by mbtools** [comment]
We need #18 to be included. Please merge and tag a new release. Thx

**Comment by jesseward** [comment]
@ashishonce and @narula0781 : it looks like this is a higher priority now due to the `set-env` changes as well. Please see the commenary within https://github.com/Azure/aci-deploy/issues/22 as well..

**Comment by nosvalds** [comment]
Please also take note of issue https://github.com/Azure/aci-deploy/issues/28 when doing the next release. node_modules needs to be checked in for the update to @actions/core to be included:

**Comment by brenoalvs** [comment]
@jesseward can I help with anything to release faster?

**Comment by jesseward** [comment]
> @jesseward can I help with anything to release faster?

hi @brenoalvs , this ticket was created to request a new release. I am not a project owner (just a consumer ;-) ). I have pinged the owners of the project in the issue comments

**Comment by brenoalvs** [comment]
@jesseward Oh sorry, I forgot to check.
@mitsha-microsoft It seems that you're the guy. There's anything I can help you?

**Comment by joelrozen** [comment]
+1 waiting for this

**Comment by mitsha-microsoft** [comment]
@brenoalvs I am not the current owner now. I wrote the action. @narula0781 @ashishonce  own this now 😄 Tagged them here

**Comment by Karishma-Tiwari-MSFT** [comment]
@narula0781 and @ashishonce Is this issue being fixed? Please let me know.
We have customers who are unable to deploy to Azure ACI using GitHub action.

**Comment by JoeMarkov** [comment]
My builds are all down too. 👎

**Comment by macolso** [comment]
👋 hi folks - from the ACI team here. This issue is under investigation

If you'd like to provide feedback on the Action here is a short [5-minute form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR4yAt620nHpGvlqiqwfbCptURFZPNjI2SFAwWVlFNDBFN0lJVTY3MjZUNC4u)

**Comment by romil07** [comment]
I have made the required changes.
Please try out the latest changes using the same version v1 and it should work.

**Comment by JoeMarkov** [comment]
Works for me :-)

**Comment by jesseward** [comment]
Confirmed working here as well. Thanks for the updates

**Comment by romil07** [comment]
Thanks for confirming. I am closing this issue.

**Comment by anraghun** [comment]
Closing the issue
