### ISSUE TITLE
Secure Environment Variables not stored registered as secure in ACI

### ISSUE THREAD

**Issue by dbrooks5** [Azure/aci-deploy#42]
Environment variables that are registered using the secure-environment-variables syntax are grouped together with the environment-variables and the values of the variable are visible in plain text in the container properties.

**Comment by kanika1894** [comment]
hey @dbrooks5, can you provide more context around the issue?
An example/sample run will be great :)

**Comment by prein** [comment]
@kanika1894 please find more context in #47

**Comment by kanika1894** [comment]
Closing this as a duplicate issue with more details exists https://github.com/Azure/aci-deploy/issues/47
