### ISSUE TITLE
Multi Container Groups

### ISSUE THREAD

**Issue by aylmerbritto** [Azure/aci-deploy#48]
I have to run an application that is dependent on three docker images that communicate to each other. 
While we are able to create a new multi-container group using a YAML where the developer mentions the configurations of multiple images. `az contianer --name <> --resource-group <> --file <>`
Our Azure/aci-delpoy does not have a file argument here. 
Does Azure/aci-deploy support multiple container group deployment? If so please help me understand how to do that?

**Comment by SteveMaier-IRT** [comment]
docker-compose can also do this for multiple images into a single container.  The source code for this action has it where it is setting the array of images to an array of a single object instead of multiple.

**Comment by aylmerbritto** [comment]
Hey @SteveMaier-IRT , 
I didn't quite understand what I have been doing wrong. If you don't mind can you please have a [look at this] 
`on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v1
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: <url>
            username: <username>
            password: <pwd>
        - run: |
            docker-compose build
            docker push #image1
            docker push #image2
        - name: 'Deploy to Rabit'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: <resource-group>
            dns-name-label: <domain-name>
            environment-variables: C_FORCE_ROOT=yes, APP_ENV=Production
            image: image1
            #command-line: celery worker -B -A simulator.tasks.celery --loglevel=debug
            location: uksouth
            name: crisismodellingmulti
            ports: 8000, 5672, 15672, 15692
            protocol: TCP
            registry-login-server: <url>
            registry-username: <unmae>
            registry-password: <pwd>
            restart-policy: Always`
 and let me know what can be done?
The issue is, I can bring only one image up. while I have to launch containers from three images. 
I manually deploy the app using aci.yml file `

The command I use is `az container create --resource-group <> --file aci.yml`. I have all three containers running if I launch it manually using the yaml file. But there's no provision for me to pass the aci.yml here.

**Comment by SteveMaier-IRT** [comment]
Hey @aylmerbritto,

I do not think you are doing anything wrong.  the aci-deploy command does not support multiple images in a single container group.  There are other people that have forked this project that have different implementations to be able to have a single container group with multiple images inside of it.  For my issue that I am seeing I am just deploying them to 3 separate containers until this gets fixed or until I look at all of the forks of the github action and see which one would work the best for me.

**Comment by aylmerbritto** [comment]
Alright, thank you @SteveMaier-IRT 
I understand. 
I know it's too much to ask but can you point me to any of the forked repositories that deploy multiple images in a single container group?
Also, you mentioned that you had deployed 

> single container group with multiple images inside of it

May I ask how did you do that? Because even if you manage to mention the images in an array, I have different commands that have to run while these containers are launching. How do I map each command to the respective images?

**Comment by SteveMaier-IRT** [comment]
https://github.com/PierreVH2/azure-containergroup-deploy/

This one seems pretty good and also has the ability to have separate command lines for each container.  look in the source for it in the taskparameters.ts to see how it is loading up the containers.  Each one can have its own image, command, evironment variables, etc.  Looks like it should work ok.  I am going to play with it for abit as well.

**Comment by aylmerbritto** [comment]
This means alot. I will try it and let know you either ways :)

**Comment by kanika1894** [comment]
Thanks a lot, @SteveMaier-IRT for your inputs.
