### ISSUE TITLE
Setup SSL Sidecar with Nginx

### ISSUE THREAD

**Issue by rwetzeler** [Azure/aci-deploy#5]
Following this: 
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-container-group-ssl

I'd like to deploy a asp.net core web app with SSL support via Nginx sidecar.  However, there doesn't seem to be a way to either specify a yml/yaml file with this config or as an input in the action.yml.  If you had an action UseSSL: Nginx as a value, that would be great for it to do it for me else have an action for file: myapp.yaml and pass in the base64 encode certs and nginx.conf.

**Comment by audit-tech-ag** [comment]
Maybe to make it even more of a general case, the capability to deploy an azure container group.
or to have the yaml file as input for the command

**Comment by kanika1894** [comment]
@N-Usha Enhancement issue, any insights on this?

**Comment by jiyangye** [comment]
> Maybe to make it even more of a general case, the capability to deploy an azure container group.
> or to have the yaml file as input for the command

It would be great if it can deploy an azure container group.

**Comment by BALAGA-GAYATRI** [comment]
Closing this issue as it is a duplicate for https://github.com/Azure/aci-deploy/issues/63. Feel free to reopen in case of any other issue. Thank you!
