### ISSUE TITLE
Add support for using a configuration file

### ISSUE THREAD

**Issue by NachoVazquez** [Azure/aci-deploy#63]
## The Problem

This action adds support for the basic **Azure CLI** deploy commands. However, there are some circumstances like supporting multiple volumes or configuring the container's resources (CPU, RAM) where the **Azure CLI**, and therefore this action, are unable to address.

The Azure CLI solves these limitations using the file configuration option

```bash
# Deploy with YAML template
az container create --resource-group myResourceGroup --file deploy-aci.yaml
```

## The solution

Add support for the file configuration in this action.

https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups?tabs=json

## Related Issues

https://github.com/Azure/aci-deploy/issues/62

**Comment by obayesshelton** [comment]
@kanika1894 is this something being put into production? I need the ability to add more than one volume

**Comment by MaslinuPoimal** [comment]
Can this be prioritized? Currently the action is very limited because for example we cannot deploy sidecar containers and have to use the CLI way instead.

**Comment by BALAGA-GAYATRI** [comment]
You can leverage that option using `azure/cli@v1` action where you will be providing the required command with arguments in the `inlineScript` and executing it. Closing it as we have an alternative for this use case.
