### ISSUE TITLE
Start, Stop and Restart container instances

### ISSUE THREAD

**Issue by klacol** [Azure/aci-deploy#66]
Hi, this is a great action. I need also to start, stop and restart the instances. Therefore I would need a wrapper for 

```shell
az container start
az container stop
az container restart
```
Is it in the scope of this action to wrap this commands, or would it better to make another action for that?

**Comment by BALAGA-GAYATRI** [comment]
Hey @klacol. You may use [azure cli action](https://github.com/Azure/cli) to execute these commands. Let us know if it solves your problem :)

**Comment by klacol** [comment]
Her @BALAGA-GAYATRI , thanks, that is exactly what I did. I wrote my first Action:

> **Azure Container Instance Operations**
> A Github Action to start, stop and restart containers in the Azure Container Instances (ACI) using the az container command.
> https://github.com/klacol/AzContainerOperations-Action
