### ISSUE TITLE
Container App: CI deploy from GitHub failing after transferring ownership

### ISSUE THREAD

**Issue by timschonborn** [Azure/aci-deploy#70]
For some reason the 'deploy' step of the CI workflow keeps failing with the following error:
```
Run azure/login@v1
  with:
    creds: ***
    enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
/usr/bin/az cloud set -n azurecloud
Done setting cloud: "azurecloud"
Error: : No subscriptions found for ***.

Error: Az CLI Login failed. Please check the credentials. For more information refer aka.ms/create-secrets-for-GitHub-workflows
```
The workflow.yml has automatically been created after setting up CI in the Azure Container Apps Page. I have registered the application in AAD and added a secret to the CI. I can see that the secrets.AZURE_CREDENTIALS value is also updated together with the workflow (and the registry credentials). The App registration has the "Cloud application administrator" role.
I've deleted and recreated the Container App & AAD registration multiple times without luck.

The only thing that comes to my mind is that 2 days ago ownership of the subscription was transferred to me, not sure if that could be causing any problems?

I've configured these workflows for a few GitHub repositories, including this repository without any issues so I'm really not sure what's going on. Maybe it's just me messing up somewhere in the process, please let me know if you have any ideas about what I could be doing wrong this time. Thanks!

Edit: I tried running the workflow with the `allow-no-subscriptions: true` setting, however, now the deployment fails a few steps later: `ERROR: cli.azure.cli.core.azclierror: The containerapp 'actions-test-app' does not exist` (created a new test Container App).

**Comment by AjayKaleMS** [comment]
Hi @tjschonborn - From the details you provided, this issue primarily falls in Az-Login repo. With this reason, I am going to close this issue.

Request you to please open a new issue in Azure/Login repo, where we can work on it relevantly.

Thanks for your cooperation.

**Comment by timschonborn** [comment]
@AjayKaleMS alright, thanks for getting back to me!
