### ISSUE TITLE
Removing JS from version control

### ISSUE THREAD

**Issue by shubham1172** [Azure/aci-deploy#71]
The source of truth for this repository is typescript code which is transpiled into JavaScript. Since we are storing both TS and JS code (which is derived from the former), it leads to issues like https://github.com/Azure/aci-deploy/pull/59

Question: why are we storing JS? Can we do without it?

**Comment by shubham1172** [comment]
Also, the `lib` folder name does not sound right. It should be generated in a `build` folder instead.

**Comment by AjayKaleMS** [comment]
Hi @shubham1172 - We shall look into this enhancement request and keep you posted.
Thanks

**Comment by shubham1172** [comment]
@AjayKaleMS, thanks! Let me know if you have any thoughts, happy to send out a PR.

**Comment by BALAGA-GAYATRI** [comment]
@shubham1172 We need either .js/ docker images/ shell script for the execution of action. Please refer [this](https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions) for the type of custom actions. So we need js files. And `lib` naming convention is followed for all the azure actions and changing it right way will be difficult. We shall definitely work on your suggestion for renaming this folder.

**Comment by shubham1172** [comment]
Sure, that's fine - another way to temporarily mitigate this is to add a step in the repository's CI, that builds and verifies the `lib` directory. This ensures that there is no delta between the `lib` in source code and the `lib` generated from actual typescript files.
