### ISSUE TITLE
This issue is marked need-to-triage for generating issues report.

### ISSUE THREAD

**Issue by dino801** [Azure/aci-deploy#72]
This issue is marked need-to-triage for generating issues report.

_Originally posted by @github-actions[bot] in https://github.com/Azure/aci-deploy/issues/39#issuecomment-852875120_

**Comment by BALAGA-GAYATRI** [comment]
@dino801 Can you explain your issue in detail?

**Comment by BALAGA-GAYATRI** [comment]
Closing this issue as the problem statement is unclear. Feel free to reopen it if you have any issues using this action.
